apiVersion: v2
name: odk-central
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: redis
    version: "16.13.2"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: "11.9.13"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.disabled
  - name: traefik
    version: 25.0.0
    repository: https://helm.traefik.io/traefik
    condition: traefik.enabled