name: "ODK Service Push"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        type: environment
        default: dev
        required: true
      docker_tag:
        description: "Image TAG (branch name will be included automatically)"
        type: text
        required: false

env:
  DOCKERHUB_TOKEN: "${{secrets.DOCKERHUB_TOKEN}}"
  DOCKERHUB_USER: "${{secrets.DOCKERHUB_USER}}"
  ODK_SERVICE_REPOSITORY: "${{vars.ODK_SERVICE_REPOSITORY}}"
  DOCKERFILE_PATH: "."
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  TAG: "${{ github.event.inputs.docker_tag }}"

jobs:
  deployment:
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          TAG=$([[ -z "${{env.TAG}}" ]] && echo "${{env.BRANCH_NAME}}" || echo "${{env.BRANCH_NAME}}-${{env.TAG}}" )
          echo "Tag: $TAG"
          chmod +x .github/workflows/odk-service-build.sh
          .github/workflows/odk-service-build.sh -r "$ODK_SERVICE_REPOSITORY" -u "$DOCKERHUB_USER" -t "$DOCKERHUB_TOKEN" -T "$TAG" -p "$DOCKERFILE_PATH"
